# Generated by Django 5.2.15 on 2026-06-22 21:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_product_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cidade_assinatura',
            field=models.CharField(default='Fortaleza/CE', max_length=80),
        ),
        migrations.AddField(
            model_name='contrato',
            name='com_profissional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_vencimento_saldo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='endereco_evento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prazo_chopeira_horas',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='contrato',
            name='quantidade_profissionais',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrato',
            name='taxa_nova_instalacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_modelo',
            field=models.CharField(choices=[('chopeira_eletrica', 'Chopeira elétrica'), ('servico_comodato', 'Prestação de serviços e comodato'), ('personalizado', 'Documento personalizado')], default='chopeira_eletrica', max_length=30),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_hora_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='documento_modelo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/modelos/'),
        ),
    ]
