# Generated by Django 5.2.15 on 2026-06-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_standard_contract_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_modelo',
            field=models.CharField(choices=[('chopeira_eletrica', 'Chopeira elétrica'), ('casamento', 'Casamento'), ('contrato_modelo', 'Contrato modelo'), ('servico_comodato', 'Prestação de serviços e comodato'), ('personalizado', 'Documento personalizado')], default='chopeira_eletrica', max_length=30),
        ),
    ]
