# Generated by Django 5.2.14 on 2026-05-27 23:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=120)),
                ('endereco_residencial', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Dona do Chopp', max_length=120)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('texto_padrao_orcamento', models.TextField(default='Segue orçamento solicitado para {{nome_cliente}}. Produtos: {{produtos}}. Serviços: {{servicos}}.')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_assinatura', 'Aguardando assinatura'), ('assinado', 'Assinado'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=30)),
                ('documento_modelo', models.FileField(upload_to='documentos/modelos/')),
                ('documento_final', models.FileField(blank=True, null=True, upload_to='documentos/finais/')),
                ('placeholders', models.JSONField(blank=True, default=list)),
                ('valores_preenchidos', models.JSONField(blank=True, default=dict)),
                ('data_assinatura_cliente', models.DateField(blank=True, null=True)),
                ('data_assinatura_usuario', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='comercial.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('endereco_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('completo', 'Completo'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('bomba_opcao', models.CharField(blank=True, choices=[('choppeira_eletrica', 'Choppeira Elétrica'), ('choppeira_bomba', 'Choppeira Bomba')], max_length=30, null=True)),
                ('profissional', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('boleto', 'Boleto')], default='pix', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='comercial.cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='comercial.contrato')),
            ],
            options={
                'ordering': ['data', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('validade', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('boleto', 'Boleto')], default='pix', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='orcamentos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='comercial.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.orcamento'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('disponivel', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_quantidade', models.PositiveIntegerField(default=0)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('lt', 'Litros'), ('m', 'Metro'), ('m2', 'Metro quadrado'), ('kg', 'Quilo')], default='un', max_length=10)),
                ('medida', models.CharField(blank=True, max_length=80)),
                ('litros', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='comercial.marca')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='comercial.orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.produto')),
            ],
        ),
        migrations.CreateModel(
            name='EventoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='comercial.evento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.produto')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='comercial.orcamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.servico')),
            ],
        ),
        migrations.CreateModel(
            name='EventoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='comercial.evento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.servico')),
            ],
        ),
    ]
