# Generated by Django 5.2.15 on 2026-06-08 23:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_companyemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='duracao_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_profissionais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], default='produto', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='meio_pagamento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_quantidade',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='comercial.marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('lt', 'Litros'), ('m', 'Metro'), ('m2', 'Metro quadrado'), ('kg', 'Quilo'), ('h', 'Hora'), ('diaria', 'Diária')], default='un', max_length=10),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='data_pagamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
